In [1]:
import pandas as pd

In [20]:
# import csv file as dataframe
xanew = pd.read_csv('/projects/MINDLAB2022_MR-semantics-of-depression/scripts/bachelor_scripts/analysis/word_stim_tsv_files/Ratings_Warriner_et_al.csv')

xanew.iloc[-9:,]

/tmp/ipykernel_1504/91840861.py:2: DtypeWarning: Columns (66) have mixed types. Specify dtype option on import or set low_memory=False.
  xanew = pd.read_csv('/projects/MINDLAB2022_MR-semantics-of-depression/scripts/bachelor_scripts/analysis/word_stim_tsv_files/Ratings_Warriner_et_al.csv')

,Unnamed: 0.1,Unnamed: 0,Word,V.Mean.Sum,V.SD.Sum,V.Rat.Sum,A.Mean.Sum,A.SD.Sum,A.Rat.Sum,D.Mean.Sum,...,A.Mean.H,A.SD.H,A.Rat.H,D.Mean.L,D.SD.L,D.Rat.L,D.Mean.H,D.SD.H,D.Rat.H,trial_type
13916,13916,NaN,Homesickness,2.70,NaN,NaN,4.85,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional
13917,13917,NaN,Coolness,6.30,NaN,NaN,4.70,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional
13918,13918,NaN,Legality,5.10,NaN,NaN,3.65,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neutral
13919,13919,NaN,Reading,6.15,NaN,NaN,2.95,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional
13920,13920,NaN,Addition,5.65,NaN,NaN,3.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neutral
13921,13921,NaN,Friday,7.70,NaN,NaN,6.70,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional
13922,13922,NaN,Firework,4.75,NaN,NaN,3.75,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neutral
13923,13923,NaN,Whiteness,6.95,NaN,NaN,7.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional
13924,13924,NaN,Joviality,7.75,NaN,NaN,5.65,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional

In [21]:
words = ['someone','homesickness','coolness','legality','reading','addition','friday','firework','whiteness','joviality']

neutral = ['someone','legality','reading','addition','whiteness']         
emotional = ['homesickness','friday','firework','joviality','coolness']

# list of all unique characters in all columns

In [22]:
# read google forms responses in
forms_resps = pd.read_csv('/projects/MINDLAB2022_MR-semantics-of-depression/scripts/bachelor_scripts/analysis/word_stim_tsv_files/google_forms_resps_19.csv', sep=';')

In [23]:
forms_resps

,Tidsstempel,Please make up a unique ID,Someone,Homesickness,Coolness,Legality,Reading,Addition,Friday,Whiteness,...,Someone.2,Homesickness.2,Coolness.2,Legality.2,Reading.2,Addition.2,Friday.2,Whiteness.2,Firework.2,Joviality.2
0,12/6/2022 12.00.31,Test,5,6,8,7,6,5,8,7,...,Emotional,Neutral,Neutral,Neutral,Emotional,Neutral,Emotional,Emotional,Emotional,Emotional
1,12/6/2022 12.14.44,hallÃ¸jsafrafÃ¸rstesal,6,2,8,7,6,6,7,5,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Neutral,Neutral,Emotional,Emotional
2,12/6/2022 12.15.37,Jhqwo,5,3,7,3,5,5,5,3,...,Neutral,Emotional,Neutral,Neutral,Neutral,Neutral,Neutral,Emotional,Neutral,Neutral
3,12/6/2022 12.23.08,567,5,2,3,4,7,5,7,5,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Emotional,Neutral,Neutral,Neutral
4,12/6/2022 12.28.25,LFP1506,5,3,8,8,7,7,9,5,...,Neutral,Emotional,Emotional,Emotional,Emotional,Emotional,Emotional,Neutral,Emotional,Neutral
5,12/6/2022 12.36.35,Kristiane,6,3,8,4,6,5,9,5,...,Emotional,Emotional,Emotional,Neutral,Neutral,Neutral,Emotional,Neutral,Emotional,Emotional
6,12/6/2022 12.39.08,BB349,6,2,8,6,8,8,10,6,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Emotional,Neutral,Emotional,Emotional
7,12/6/2022 12.41.58,gGiOP,5,3,6,5,8,6,7,1,...,Neutral,Emotional,Neutral,Neutral,Neutral,Neutral,Emotional,Emotional,Emotional,Emotional
8,12/6/2022 12.43.09,5436,5,2,8,5,5,5,8,5,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Emotional,Neutral,Neutral,Emotional
9,12/6/2022 12.44.24,sjÃ¥lÃ¥lÃ¥,5,2,6,5,5,5,7,5,...,Neutral,Emotional,Neutral,Neutral,Neutral,Neutral,Emotional,Neutral,Neutral,Emotional
10,12/6/2022 12.44.42,letsgoooooo,5,3,5,5,6,5,8,5,...,Neutral,Emotional,Neutral,Neutral,Neutral,Neutral,Emotional,Neutral,Emotional,Emotional
11,12/6/2022 13.02.54,789234hj,6,3,6,5,7,6,9,5,...,Emotional,Emotional,Emotional,Neutral,Emotional,Neutral,Emotional,Emotional,Emotional,Emotional
12,12/6/2022 13.16.56,mf1113,5,4,3,5,6,6,8,5,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Emotional
13,12/6/2022 13.46.28,696969,6,2,6,5,7,6,7,6,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Emotional,Emotional,Emotional,Emotional
14,12/6/2022 14.02.43,skrrtmoney,6,3,6,4,6,5,7,5,...,Neutral,Emotional,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Emotional
15,12/6/2022 18.45.58,0999,5,2,5,4,5,6,8,3,...,Neutral,Emotional,Neutral,Neutral,Neutral,Neutral,Emotional,Emotional,Neutral,Emotional
16,12/7/2022 10.25.46,Jack Sparrow,5,2,6,4,6,4,8,4,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Neutral,Neutral,Neutral,Emotional
17,12/7/2022 11.15.28,8177818,5,3,7,6,5,5,7,5,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Emotional,Neutral,Emotional,Emotional
18,12/7/2022 11.25.40,uniktID1234,8,1,5,5,5,8,10,5,...,Emotional,Emotional,Emotional,Neutral,Emotional,Emotional,Emotional,Neutral,Emotional,Emotional
19,12/7/2022 12.33.25,Wert1234,5,3,7,5,7,5,5,5,...,Neutral,Emotional,Emotional,Neutral,Neutral,Neutral,Neutral,Neutral,Emotional,Emotional

In [24]:
# compute mean for all columns with names not endning with .1
valence_means = forms_resps.filter(regex='^(?!.*\.1$).*$').mean()
valence_means

/tmp/ipykernel_1504/1657443337.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  valence_means = forms_resps.filter(regex='^(?!.*\.1$).*$').mean()

Someone         5.45
Homesickness    2.70
Coolness        6.30
Legality        5.10
Reading         6.15
Addition        5.65
Friday          7.70
Whiteness       4.75
Firework        6.95
Joviality       7.75
dtype: float64

In [25]:
# compute mean for all columns with names ending with .1
arousal_means = forms_resps.filter(regex='.*\.1$').mean()
arousal_means

Someone.1         3.00
Homesickness.1    4.85
Coolness.1        4.70
Legality.1        3.65
Reading.1         2.95
Addition.1        3.60
Friday.1          6.70
Whiteness.1       3.75
Firework.1        7.60
Joviality.1       5.65
dtype: float64

In [26]:
column_names = ['Someone','Homesickness.2','Coolness.2','Legality.2','Reading.2','Addition.2','Friday.2','Whiteness.2','Firework.2','Joviality.2']
column_names

for i in column_names:
    print(forms_resps[i].value_counts())

5    13
6     6
8     1
Name: Someone, dtype: int64
Emotional    19
Neutral       1
Name: Homesickness.2, dtype: int64
Emotional    13
Neutral       7
Name: Coolness.2, dtype: int64
Neutral      19
Emotional     1
Name: Legality.2, dtype: int64
Neutral      16
Emotional     4
Name: Reading.2, dtype: int64
Neutral      18
Emotional     2
Name: Addition.2, dtype: int64
Emotional    14
Neutral       6
Name: Friday.2, dtype: int64
Neutral      14
Emotional     6
Name: Whiteness.2, dtype: int64
Emotional    12
Neutral       8
Name: Firework.2, dtype: int64
Emotional    17
Neutral       3
Name: Joviality.2, dtype: int64

In [27]:
# count number of different unique responses for the last 10 columns in the dataframe and percentages
for i in column_names:
    print(forms_resps[i].value_counts(normalize=True))

5    0.65
6    0.30
8    0.05
Name: Someone, dtype: float64
Emotional    0.95
Neutral      0.05
Name: Homesickness.2, dtype: float64
Emotional    0.65
Neutral      0.35
Name: Coolness.2, dtype: float64
Neutral      0.95
Emotional    0.05
Name: Legality.2, dtype: float64
Neutral      0.8
Emotional    0.2
Name: Reading.2, dtype: float64
Neutral      0.9
Emotional    0.1
Name: Addition.2, dtype: float64
Emotional    0.7
Neutral      0.3
Name: Friday.2, dtype: float64
Neutral      0.7
Emotional    0.3
Name: Whiteness.2, dtype: float64
Emotional    0.6
Neutral      0.4
Name: Firework.2, dtype: float64
Emotional    0.85
Neutral      0.15
Name: Joviality.2, dtype: float64

In [28]:
# make valence_means a list
valence = valence_means.tolist()
arousal = arousal_means.tolist()
words = words

In [29]:
# combine valence, arousal, and words to dataframe
df = pd.DataFrame(list(zip(words, valence, arousal)), columns =['Words', 'Valence', 'Arousal'])
df

          Words  Valence  Arousal
0       someone     5.45     3.00
1  homesickness     2.70     4.85
2      coolness     6.30     4.70
3      legality     5.10     3.65
4       reading     6.15     2.95
5      addition     5.65     3.60
6        friday     7.70     6.70
7      firework     4.75     3.75
8     whiteness     6.95     7.60
9     joviality     7.75     5.65

In [30]:
df['trial_type'] = 'Neutral'
df.loc[(df['Arousal'] > 2) & (df['Valence'] < 3), 'trial_type'] = 'Emotional' 
df.loc[(df['Arousal'] > 2) & (df['Valence'] > 6), 'trial_type'] = 'Emotional'

In [31]:
df # in the binary response, people disagree with reading (80N/ 20E), firework (60E/40E), whiteness (30N, 70E) 

# rename "Words" column to "word"
df.rename(columns={'Words':'Word'}, inplace=True)
df.rename(columns={'Valence':'V.Mean.Sum'}, inplace=True)
df.rename(columns={'Arousal':'A.Mean.Sum'}, inplace=True)

In [32]:
df

           Word  V.Mean.Sum  A.Mean.Sum trial_type
0       someone        5.45        3.00    Neutral
1  homesickness        2.70        4.85  Emotional
2      coolness        6.30        4.70  Emotional
3      legality        5.10        3.65    Neutral
4       reading        6.15        2.95  Emotional
5      addition        5.65        3.60    Neutral
6        friday        7.70        6.70  Emotional
7      firework        4.75        3.75    Neutral
8     whiteness        6.95        7.60  Emotional
9     joviality        7.75        5.65  Emotional

In [33]:
# add Word column from df to xanew as rows
xanew = xanew.append(df, ignore_index=True)

/tmp/ipykernel_1504/2919937518.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  xanew = xanew.append(df, ignore_index=True)

In [34]:
xanew

,Unnamed: 0.1,Unnamed: 0,Word,V.Mean.Sum,V.SD.Sum,V.Rat.Sum,A.Mean.Sum,A.SD.Sum,A.Rat.Sum,D.Mean.Sum,...,A.Mean.H,A.SD.H,A.Rat.H,D.Mean.L,D.SD.L,D.Rat.L,D.Mean.H,D.SD.H,D.Rat.H,trial_type
0,0.0,1.0,aardvark,6.26,2.21,19.0,2.41,1.40,22.0,4.27,...,2.55,1.29,11.0,4.12,1.64,8.0,4.43,1.99,7.0,NaN
1,1.0,2.0,abalone,5.30,1.59,20.0,2.65,1.90,20.0,4.95,...,2.38,1.92,8.0,5.55,2.21,11.0,4.36,1.03,11.0,NaN
2,2.0,3.0,abandon,2.84,1.54,19.0,3.73,2.43,22.0,3.32,...,3.82,2.14,11.0,2.77,2.09,13.0,4.11,2.93,9.0,NaN
3,3.0,4.0,abandonment,2.63,1.74,19.0,4.95,2.64,21.0,2.64,...,5.29,2.63,7.0,2.31,1.45,16.0,3.08,2.19,12.0,NaN
4,4.0,5.0,abbey,5.85,1.69,20.0,2.20,1.70,20.0,5.00,...,2.55,1.92,11.0,4.83,2.18,18.0,5.43,1.62,7.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13930,NaN,NaN,addition,5.65,NaN,NaN,3.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neutral
13931,NaN,NaN,friday,7.70,NaN,NaN,6.70,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional
13932,NaN,NaN,firework,4.75,NaN,NaN,3.75,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neutral
13933,NaN,NaN,whiteness,6.95,NaN,NaN,7.60,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional
13934,NaN,NaN,joviality,7.75,NaN,NaN,5.65,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Emotional

In [35]:

xanew.to_csv('Ratings_Warriner_et_al.csv')